# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20180817_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='hosts',
            field=models.ManyToManyField(blank=True, null=True, related_name='cabinet_hosts', to='source.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='host',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_application', to='source.Application', verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='host',
            name='colony',
            field=models.ManyToManyField(blank=True, null=True, related_name='host_colony', to='source.Colony', verbose_name='所属集群'),
        ),
        migrations.AlterField(
            model_name='host',
            name='systemuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_systemuser', to='source.SystemUser', verbose_name='系统用户'),
        ),
    ]
