# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20180817_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'default_permissions': (), 'permissions': (('list_application', '获取应用列表'), ('get_application', '获取应用信息'), ('add_application', '添加应用'), ('change_application', '修改应用信息'), ('delete_application', '删除应用')), 'verbose_name': '应用', 'verbose_name_plural': '应用'},
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
