# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20180817_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colony',
            options={'default_permissions': (), 'permissions': (('list_hostgroup', '获取集群列表'), ('get_hostgroup', '获取集群信息'), ('add_hostgroup', '添加集群'), ('change_hostgroup', '修改集群信息'), ('delete_hostgroup', '删除集群')), 'verbose_name': '集群', 'verbose_name_plural': '集群'},
        ),
    ]
