# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_auto_20180817_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='colony',
            field=models.ManyToManyField(blank=True, related_name='host_colony', to='source.Colony', verbose_name='所属集群'),
        ),
    ]
