# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20180819_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='cabinet_hosts', to='source.Host', verbose_name='主机'),
        ),
    ]
