# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(null=True, related_name='role_perm', to='auth.Permission', verbose_name='角色权限'),
        ),
    ]
