# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180817_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='role_perm', to='auth.Permission', verbose_name='角色权限'),
        ),
    ]
